#:kivy 2.0.0
<ViewEresources>
    FloatLayout:
        MDLabel:
            text: "A.S.Naik"
            pos_hint: {'center_x':0.15,'center_y':0.95}
            size_hint: (0.2,0.2)
        MDLabel:
            text: "IT"
            pos_hint: {'center_x':0.95,'center_y':0.95}
            size_hint: (0.2,0.2)
        MDLabel:
            text: "E-Resources"
            pos_hint: {'center_x':0.5,'center_y':0.85}
            font_style: 'H2'
            halign: 'center'